backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "სათაური", name: "title", widget: "string" }
      - { label: "აღწერა", name: "description", widget: "string" }
      - { label: "გამოქვეყნების თარიღი", name: "date", widget: "datetime" }
      - { label: "თეგები", name: "tags", widget: "list", default: ["post", "featured"] }
      - { label: "სურათი", name: "image", widget: "image" }
      - { label: "სურათის სახელწოდება", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "founders"
    label: "Founders"
    folder: "src/founders"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "name", label: "სახელი", widget: "string" }
      - { name: "surename", label: "გვარი", widget: "string" }
      - { name: "position", label: "პოზიცია", widget: "string" }
      - { label: "თეგები", name: "tags", widget: "list", default: ["founders"] }
      - { name: "img", label: "სურათი", widget: "image" }
      

